config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "links#index"
  resources :links
  resources :views, path: :v, only: [:show] # /v/:id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/base62.rb
class Base62
  CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = CHARS.length
  # Returns a string ex: Base62.encode(1064) = "gw"
  def self.encode(number)
    return "0" if number == 0 || number == nil 
    result = ""

    while number > 0 do
      result.prepend(CHARS[number % BASE])
      number = number / BASE
      # require "pry"
      # binding.pry
    end
    result
  end

  # Returns a number ex: Base62.decode("gw") = 1062
  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do | char, index |
      power = BASE**index 
      index = CHARS.index(char)
      number += index * power
    end
    
    number
  end
end

# Call the encode method
# encoded_string = Base62.encode(1024)

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  validates :url, presence: true

  scope :recent_first, -> { order(created_at: :desc) }

  # Overwriting default find method to decode back to integer
  def self.find(id)
    super Base62.decode(id)
  end


  # Overwriting default to_param method
  # it returns a base62 encoded string instead of an id
  def to_param
    Base62.encode(id)
  end

end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_link
    @link = Link.find(params[:id])
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]
  def index
    @links = Link.recent_first
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path
    else
      render :index, status: :unprocessable_entity
    end

  end

  def show
 
  end

  private
    def link_params
      params.require(:link).permit(:url)
    end

  end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  def show
    @link.views.create!(
      ip: request.ip,
      user_agent: request.user_agent,
    )
    # Because we're using the `allow_other_host` option, we can redirect to any URL (external)
    redirect_to @link.url, allow_other_host: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_link.html.erb
  <ul>
  <% @links.each do |link| %>
    <li id=<%= dom_id(link)%>>
     <%= link_to link.to_param, link %>
     <%= link.url %>
     <%= link.views_count %>

     <%= link_to view_path(link), target: :_blank, data: {turbo: false} do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
      </svg>

     <% end %>
    </li>
  <% end %>
  </ul>

  

app/views/links/index.html.erb
<h1>URL Shortener</h1>

<%= form_with model: Link.new do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, required: true, autofocus: true, placeholder: "https://yomama.com", class: "rounded flex-1" %>
    <%= form.button "Save", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

<% if @links.any? %>
  <%= render "link"%>
<% end %>

app/views/links/show.html.erb
<h2>YO</h2>
<p><%= @link.url %></p>